#VM1
[root@localhost ~]# ip link set eth0 up
[root@localhost ~]# ip a add 192.168.0.1/24 dev eth0
[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:17:d3:b6 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe17:d3b6/64 scope link 
       valid_lft forever preferred_lft forever

[root@localhost ~]# vim /etc/named.conf
[root@localhost ~]# cat /etc/named.conf 
'//
// named.conf
//
// Provided by Red Hat bind package to configure the ISC BIND named(8) DNS
// server as a caching only nameserver (as a localhost DNS resolver only).
//
// See /usr/share/doc/bind*/sample/ for example named configuration files.
//
// See the BIND Administrators Reference Manual (ARM) for details about the
// configuration located in /usr/share/doc/bind-{version}/Bv9ARM.html

options {
	listen-on port 53 { any; };
	listen-on-v6 port 53 { any; };
	directory 	"/var/named";
	dump-file 	"/var/named/data/cache_dump.db";
	statistics-file "/var/named/data/named_stats.txt";
	memstatistics-file "/var/named/data/named_mem_stats.txt";
	allow-query     { 192.168.0.0/24; };

	/* 
	 - If you are building an AUTHORITATIVE DNS server, do NOT enable recursion.
	 - If you are building a RECURSIVE (caching) DNS server, you need to enable 
	   recursion. 
	 - If your recursive DNS server has a public IP address, you MUST enable access 
	   control to limit queries to your legitimate users. Failing to do so will
	   cause your server to become part of large scale DNS amplification 
	   attacks. Implementing BCP38 within your network would greatly
	   reduce such attack surface 
	*/
	recursion no;

	dnssec-enable yes;
	dnssec-validation yes;

	/* Path to ISC DLV key */
	bindkeys-file "/etc/named.iscdlv.key";

	managed-keys-directory "/var/named/dynamic";

	pid-file "/run/named/named.pid";
	session-keyfile "/run/named/session.key";
};

logging {
        channel default_debug {
                file "data/named.run";
                severity dynamic;
        };
};

zone "." IN {
	type hint;
	file "named.ca";
};

zone "examen.es." {

	type master;
	file "db.examen.es";
};

include "/etc/named.rfc1912.zones";
include "/etc/named.root.key";
'

[root@localhost ~]# named-checkconf
[root@localhost ~]# vim /var/named/db.examen.es
[root@localhost ~]# cat /var/named/db.examen.es
$TTL 2d
$ORIGIN examen.es.
examen.es.	IN	SOA	ns.examen.es. contact.examen.es. (
			2022010400;
			3h;
			15M;
			3W12h;
			2h20M;
			)
		IN	NS	ns
		IN	MX	1	mail
ns		IN	A	192.168.0.1
www		IN	A	192.168.0.200
mail		IN	A	192.168.0.250
examen.es	IN	CNAME	mail
[root@localhost ~]# named-checkzone examen.es. /var/named/db.examen.es
[root@localhost ~]# service named start
[root@localhost ~]# service named status


#VM2
[root@localhost ~]# ip link set eth0 up
[root@localhost ~]# ip a add 192.168.0.2/24 dev eth0
[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:0b:f4:5b brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe0b:f45b/64 scope link 
       valid_lft forever preferred_lft forever

[root@localhost ~]# vim /etc/resolv.conf 
[root@localhost ~]# cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search ns.examen.es
nameserver 192.168.0.1
[root@localhost ~]# dig examen.es
'; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> examen.es
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44729
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;examen.es.			IN	A

;; AUTHORITY SECTION:
examen.es.		8400	IN	SOA	ns.examen.es. contact.examen.es. 2022010400 10800 900 1857600 8400

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jan 04 16:28:22 CET 2022
;; MSG SIZE  rcvd: 85

[root@localhost ~]# dig soa examen.ess

; <<>> DiG 9.9.4-RedHat-9.9.4-61.el7_5.1 <<>> soa examen.ess
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 10820
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;examen.ess.			IN	SOA

;; Query time: 0 msec
;; SERVER: 192.168.0.1#53(192.168.0.1)
;; WHEN: Tue Jan 04 16:28:58 CET 2022
;; MSG SIZE  rcvd: 39


